version: 2
updates:
  - package-ecosystem: "gradle" 
    directory: "/" 
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "CET"
    labels:
        - "Dependabot"
    open-pull-requests-limit: 10
