version: 0.2

env:
  variables:
    SAM_CLI_TELEMETRY: 0

phases:
  install:
    runtime-versions:
      python: 3.8
      ruby: latest
    commands:
      - which gem && gem install cfn-nag && cfn_nag_rules && cfn_nag_scan --version

  pre_build:
    commands:
      - aws s3 cp s3://$S3_BUCKET_NAME/adf-build/ adf-build/ --recursive --quiet
      - pip install -r adf-build/requirements.txt -q
      - python adf-build/generate_params.py

  build:
    commands:
      - aws cloudformation validate-template --template-body file://template.yml
      - cfn_nag_scan --input-path ./template.yml
      - bash adf-build/helpers/package_transform.sh

artifacts:
  files: "**/*"
