AWSTemplateFormatVersion: 2010-09-09
Description: Yara DST YGT CONFIGURATION DEV
Parameters:
  ProjectName:
    Description: This is the inception of the dst-ygt-configuration migration
    Type: String
  ModuleName:
    Description: Descriptive name of the module
    Type: String
  SiteName:
    Description: Site name abbreviation
    Type: String
    Default: GLO


Resources:
  ParameterDemo:
    Type: AWS::SSM::Parameter
    Properties:
      Description: "demo resource from the adf template"
      Name:
        !Join [
          ".",
          [!Ref "SiteName", "global", "demo", !Ref "ModuleName"],
        ]
      Value: "demo"
      Type: String
      Tags:
        name:
          !Join [
            "-",
            [!Ref "SiteName", "global", "demo", !Ref "ModuleName"],
          ]
