name: Run Gradle Build on commits in PR
on:
  push:
    branches-ignore:
      - main
    # run this only when there is any changes to kotlin/ dependencies
    paths:
      - '**/*.kt'
      - '*.kts'
      - 'gradle.properties'
jobs:
  clean-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 11

      - name: Setup Gradle and clean build and check coverage
        uses: gradle/gradle-build-action@v2
        with:
          arguments: clean build
